### PR TITLE
Got phi table to display

### PR DESCRIPTION
**Pull request by varriaza**
#38

I finished getting the phi table to display the corresponding waveforms and double checked that everything was were it should be by manually checking 10 random waveforms in each category. One problem is that I was not sure how I should have the clock display so I left that blank for now (they were not included in the array peng gave us). Let me know and I will update it.

Additionally I discovered that we are skipping the first set of data when we connect. To see evidence of this connect to my server at heroku (https://victoranita.herokuapp.com/) and click on the connect button. Before you do anything else notice that no waveforms appear (as should be expected). Yet if you click on the surf view button waveforms appear. Upon hitting next for the first time you will be brought to the data we normally associate as being the first entry (it is identifiable as it has the missing entry). To solve this we could either start the nbufs at one less than the first data entry to require users to click next or have the data automatically show after the user clicks on connect.

EDIT: I will be adding FFT and Power compatibility if this looks good to Peng and Dr. Seckel.

### CODE REVIEW

**Comment by dseckel** [comment]
hi -

i can see the phi layout, which is good. it doesn't seem to work with power or fft. the 
surf layout shows a power display, but not an fft display.

i'd hope that all options should work in either layout. moreover, if another layout is 
offered, one should still be able to select from all datatype options.

**Comment by sylarcp** [comment]
Great work!
Several things still need to be fixed:
1. Use as less api request as your can.
   `.getJSON('/api/' + ip_db + '/wv/'+ data.hd.evnum,` 
   should only be called once. And then depends on the value of dataview, show the different table.
2. When we switch to Phi view, try to make fft and power also work.  I suggest displaying a single waveform should be a separate callable function with datatype as an option. So phi view and surf view will reuse this same function.  
   Reuse the code is very important to readability . Avoid duplicated blocks and put them into a function.
3. Fix all the alignment format of code. It is hard to read if the bracket are not aligned.

**Comment by sylarcp** [comment]
_4. Yeah,you are right. The first event is not displayed. We just need to update html when we connect. That is the first event. And it also give user a feedback about the connection.

_5. Lower piority.  I see when you change to a different datatype ( mv, fft and power) you need to request the data again, which is not necessary. Try to reuse the data.   I think calling api, get data and put it into a data structure is a one function. Display the data is another function. In this case, the first function does not need to be recalled.

**Comment by varriaza** [comment]
Just finished adding a few different features.
-Added FFT and Power to Phi
-Cleaned up code and made it have better alignment (Peng's points 1+3)
-Created two new functions for plotting (One didn't work for some reason) and made all the functions use them (Peng's point 2)

**Pull request merged**
