### PR TITLE
Adu5 pat working

### PR DESCRIPTION
**Pull request by varriaza**
Apparently, github cannot auto merge this and we are not sure why.

### CODE REVIEW

**Comment by sylarcp** [comment]
Have you fixed all the conflicts and commit again?  Could you run it success in your computer?

**Comment by varriaza** [comment]
I have tried finding out where the conflicts are but am unsure where they are as it does not even let me merge your changes to mine. My file is very similar to yours. I can run the server fine and cannot find any "error text" in the hk.html which is where it seems to be having problems.

**Comment by sylarcp** [comment]
What is the error message when you pull?

**Comment by varriaza** [comment]
I cannot get the changes that are on your version to be put on my github account version. I cannot get to the point where I would pull. It says the same as here, that here are conflicts that must be solved.

**Pull request merged**
