### PR TITLE
Fixed Sunsensor and created power table

### PR DESCRIPTION
**Pull request by varriaza**

### CODE REVIEW

**Comment by sylarcp** [comment]
I merged Mat's pull request first. Now there are conflicts. Please fix those conflicts like what I did and commit, push. Thanks.

**Comment by varriaza** [comment]
Matt and I merged the code that we had and submitted that.

**Comment by sylarcp** [comment]
It still have conflicts, please fix it.

**Comment by mcollins12321** [comment]
You don't need to merge Victor's anymore. My commit from this afternoon
should have fixed the problems and added what he had.

**Comment by varriaza** [comment]
What Matt said.

**Comment by sylarcp** [comment]
OK, closed

**Pull request closed without merging**
